const IMAGE_TYPE_EXTENSIONS: Record<string, string> = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
  'image/gif': 'gif',
};

export const MAX_IMAGE_UPLOAD_BYTES = 5 * 1024 * 1024; // 5 MB

export type ImageValidationResult =
  | { ok: true; extension: string }
  | { ok: false; error: string };

export function validateProjectImage(contentType: string | null, size: number): ImageValidationResult {
  const extension = contentType ? IMAGE_TYPE_EXTENSIONS[contentType] : undefined;
  if (!extension) {
    return { ok: false, error: 'Unsupported image type. Use JPEG, PNG, WebP, or GIF.' };
  }
  if (size <= 0) {
    return { ok: false, error: 'Empty file.' };
  }
  if (size > MAX_IMAGE_UPLOAD_BYTES) {
    return { ok: false, error: 'Image is larger than 5 MB.' };
  }
  return { ok: true, extension };
}

/** Sanitizes an uploaded filename's basename into a URL/git-safe slug. */
export function slugifyImageBasename(filename: string): string {
  const withoutExtension = filename.replace(/\.[^.]+$/, '');
  const slug = withoutExtension
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return slug || 'image';
}

/**
 * Builds the repo-relative path for a newly uploaded image. `uniqueSuffix`
 * (a short random id, generated by the caller) is always appended so two
 * uploads with the same original filename never collide — simpler and
 * race-free compared to checking remote existence before every write.
 */
export function buildImageUploadFilePath(
  imageUploadPath: string,
  originalFilename: string,
  extension: string,
  uniqueSuffix: string,
): string {
  const prefix = imageUploadPath.replace(/^\/+|\/+$/g, '');
  const basename = slugifyImageBasename(originalFilename);
  return [prefix, `${basename}-${uniqueSuffix}.${extension}`].filter(Boolean).join('/');
}

/**
 * The Markdown-referenced URL for an uploaded image. Astro (and the default
 * `imageUploadPath` of `public/images`) serves everything under `public/` at
 * the site root, so a repo path under `public/` is referenced without that
 * prefix. Projects using a different `imageUploadPath` (e.g. a Jekyll
 * `assets/` folder, which Jekyll also serves at the site root) get the full
 * path referenced as-is. There's no reliable way to know a given SSG's
 * serving rules beyond that — this is a best-effort default the user can
 * freely edit afterward, not a guarantee.
 */
export function buildImageReferenceUrl(repoPath: string): string {
  const withoutPublicPrefix = repoPath.replace(/^public\//, '');
  return `/${withoutPublicPrefix}`;
}
